version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip